### ISSUE TITLE
Support dynamic reload of TLS certificates

### ISSUE THREAD

**Issue by andrewsykim** [vmware/hamlet#12]
It would be useful if Hamlet can support watching the paths to the TLS certificates and dynamically update the serving certificates when they change. This would allow for key rotation by simply updating the certificates on disk. 

This should be possible using inotify watchers and the `GetCertificates` field in `tls.Config`.

**Comment by akutz** [comment]
An example of how to do this can also be found in the controller-runtime at https://github.com/kubernetes-sigs/controller-runtime/blob/master/pkg/webhook/internal/certwatcher/certwatcher.go.

**Comment by andrewsykim** [comment]
Realizing now that hamlet receives a tls.Config for the server constructor so maybe it was intentionally up to the consumer of Hamlet to implement this. Either way it would be nice if Hamlet can natively support this given a certificates directory or the path to the TLS certificate/key files.

**Comment by andrewsykim** [comment]
Nvm, forgot that there's a TLS pkg here https://github.com/vmware/hamlet/tree/master/pkg/tls -- so we could potentially add the certwatch logic in there if consumers want to use it.

**Comment by sergiopozoh** [comment]
sounds good, please feel free to pr the changes
